@baseUrl = http://localhost:3000

# @name getAllCategories
GET {{baseUrl}}/products/?_page=1&_limit=12

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "pizza"
}

###
# @name updateCategory
PATCH {{baseUrl}}/categories/3
Content-Type: application/json

{
    "name": "sauces"
}

###
# @name removeCategory
DELETE {{baseUrl}}/categories/2
Content-Type: application/json

